apiVersion: v1
kind: Secret
metadata:
  name: config-bundle-secret
  namespace: quay-enterprise
stringData:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    BROWSER_API_CALLS_XHR_ONLY: false
    SUPER_USERS:
    - quayadmin
    FEATURE_USER_CREATION: true
    FEATURE_QUOTA_MANAGEMENT: true
    FEATURE_PROXY_CACHE: true
    FEATURE_BUILD_SUPPORT: true
    DEFAULT_SYSTEM_REJECT_QUOTA_BYTES: 102400000
    EXTERNAL_TLS_TERMINATION: true
    FEATURE_UI_V2: true
    AUTHENTICATION_TYPE: OIDC
    SERVICE_NAME: OpenShift OAuth
    
    # Discovery off (OpenShift’s well-known endpoint is not anonymously readable)
    OIDC_AUTOCONFIGURE: false
    
    # In-cluster OAuth endpoints
    OIDC_SERVER:             https://openshift.default.svc/oauth/
    OIDC_ENDPOINT:           https://openshift.default.svc/oauth/authorize
    OIDC_TOKEN_ENDPOINT:     https://openshift.default.svc/oauth/token
    OIDC_USER_ENDPOINT:      https://openshift.default.svc/oauth/userinfo
    OIDC_JWKS_ENDPOINT:      https://openshift.default.svc/oauth/keys
    
    # Client credentials from the OAuthClient above
    CLIENT_ID: quay-client
    CLIENT_SECRET: s3cr3tQuayCl13ntT0k3n
    
    # Claims and scopes
    OIDC_USERNAME_CLAIM: preferred_username
    OIDC_EMAIL_CLAIM: email
    OIDC_GROUPS_CLAIM: groups
    OIDC_LOGIN_SCOPES: "openid"
    
    # TLS verification: trust the cluster CA mounted in every SA
    OIDC_CACERT: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    OIDC_VERIFY_SSL: true

