apiVersion: v1
kind: Secret
metadata:
  name: config-bundle-secret
  namespace: quay-enterprise
stringData:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    BROWSER_API_CALLS_XHR_ONLY: false
    SUPER_USERS:
    - quayadmin
    FEATURE_USER_CREATION: true
    FEATURE_QUOTA_MANAGEMENT: true
    FEATURE_PROXY_CACHE: true
    FEATURE_BUILD_SUPPORT: true
    DEFAULT_SYSTEM_REJECT_QUOTA_BYTES: 102400000
    EXTERNAL_TLS_TERMINATION: true
    FEATURE_UI_V2: true
    AUTHENTICATION_TYPE: OIDC
    OPENSHIFT_LOGIN_CONFIG:
      OIDC_SERVER: https://oauth-openshift.openshift-authentication.svc/
      OIDC_ISSUER: .well-known/oauth-authorization-server
      CLIENT_ID: quay-client
      CLIENT_SECRET: s3cr3tQuayCl13ntT0k3n
      SERVICE_NAME: OpenShift OAuth
  extra_ca_cert_certificate-one: |
    -----BEGIN CERTIFICATE-----
    MIIEFDCCAvygAwIBAgIIW1sZEXZusgEwDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTc1NDkyODI5OTAe
    Fw0yNTA4MTExNjA1MjNaFw0yNzA4MTExNjA1MjRaMDcxNTAzBgNVBAMTLG9hdXRo
    LW9wZW5zaGlmdC5vcGVuc2hpZnQtYXV0aGVudGljYXRpb24uc3ZjMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtejgzfvzX3/f8SGDVscCBjWQtYrfoyFb
    1HZ5V1pNZkx+pUfHCDhoaT/9maCi3q7EpT7d8+HN6eTKAfdmDqmmXnGfoxOAQC6H
    w1HfZgx42zCitZRpS0KsfwmNIdpXqpvMZAuCMywoz9PJ4BDuPkYIOM4L9eqDuzms
    oYzLUwRXBBhnOE8NnFwjzdogqTAO5GIOFf5BnHndNCdXNCMV7PTVPscEVdc9oC1g
    TvZux+yJ5aQqg/BxKG50NVNedv6qJZivqoFHQB+MMXrXkvxzw/7W1Guw+mkI9IsO
    tZXrRasfrMEvu++C8Mctdhhsdle2Fcd3aXOSVQp0pcJb1N0hnkswpwIDAQABo4IB
    IzCCAR8wDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1Ud
    EwEB/wQCMAAwHQYDVR0OBBYEFFYc1WRsH5o6M/l3E+RSSoh7JmntMB8GA1UdIwQY
    MBaAFBG/uynrm2hIz0yp4bOGhnTlB0MiMHMGA1UdEQRsMGqCLG9hdXRoLW9wZW5z
    aGlmdC5vcGVuc2hpZnQtYXV0aGVudGljYXRpb24uc3ZjgjpvYXV0aC1vcGVuc2hp
    ZnQub3BlbnNoaWZ0LWF1dGhlbnRpY2F0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsMDUG
    CysGAQQBkggRZAIBBCYTJDY1MzdmNzBmLWEwZTEtNGIyZS1hMDgzLWYxNDhhZTI4
    NWZlNzANBgkqhkiG9w0BAQsFAAOCAQEAqDx9iFPqoYKHREZDMwXtAKNCam44UrTG
    /ZrR+F+TuKZCX6n3KWsIiDOUmwPU1/6Htf+4rUBqpsYH5nzYxvDU3UTj2YSPiqLh
    wpcYNXQOHXw+v6flPNL6vJt/5Nap5MZWZFUmVU9NA+QWCWNx4ZxF4yiFKkmmbd1L
    H1xeAI418cM+ZLQQ2SJjHHzsDYx/3MRJuEbAf61Xv4aENkHXbfZQbXpcInX6HBhn
    39/vlCZFSkP2JyPmQDhqhTkNFXhaNj7A8xvYjQLIlUhtkF+Uk7SCX++h9tV2DIp1
    3KLoL6TvFlyltMX12txmid1YLZHwl8z4TpZlaLqKDER8xIIYN5851Q==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIIJUtYOhlTZ3QwDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTc1NDkyODI5OTAe
    Fw0yNTA4MTExNjA0NThaFw0yNzEwMTAxNjA0NTlaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE3NTQ5MjgyOTkwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDrN7+SeOMCYhEKubGnEcCbB69jkYfRE/dx
    P7DC1dxrBsSnB/E7VM9efjL5697ak7SK2+PT4OI/TGnPlfWkJe9KAE4R0LVoi6v5
    HV8bKib96tQziEc4CzGAzXSxQwP2Eo2SWxrw3nj53CIdb95Y87omlpLqyiR26sCz
    erlULLEBpR81cFaJCVudZjuXQlsaQDW1F5z6NclPrwsI2tcxb/64gJE+jczOwUT2
    NKnVBC+PQMkNReBKGhtqPv1q1yxvVoj0XOumtG1t4r/FWN4bzup9Pe/42As8ovVf
    aZMgS0QgJ5A+nRubcgjWruW8HpnHEcjV7tEBT5ghbs3DUWy/TOyJAgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQRv7sp
    65toSM9MqeGzhoZ05QdDIjAfBgNVHSMEGDAWgBQRv7sp65toSM9MqeGzhoZ05QdD
    IjANBgkqhkiG9w0BAQsFAAOCAQEA57X9DoxDvEhFWcy9R7g055DfJjfZYFrYjU9I
    kIzODZ6uES+8D1UCCqFRk1loY8BMXRrX698UhvQhUnc3j+pzshk1dVPPG2zsLIWV
    H7MN4MmW1SXDzsp6HoCFGkB4/ZjxEES9G3el/zSdzBtzA1rU0MDvjOKFreWR9faa
    +IeqHf1xOivZ+ao16Naf7rRPbhLDaj+bk6+J4D8j3XfgiTojkNZBeWkwC+sPeXNx
    VhRCXz2R6yy42ytuvJ+wdQk7uGxZJKG3w8SCXQyMMN6X0qeOcqIQi1eJeHLFsZAy
    kprgwLtw/koJG1Sn/AVStWfJVhXFGKJ4F0KQZJL7F0K+0oLxOw==
    -----END CERTIFICATE-----
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAtejgzfvzX3/f8SGDVscCBjWQtYrfoyFb1HZ5V1pNZkx+pUfH
    CDhoaT/9maCi3q7EpT7d8+HN6eTKAfdmDqmmXnGfoxOAQC6Hw1HfZgx42zCitZRp
    S0KsfwmNIdpXqpvMZAuCMywoz9PJ4BDuPkYIOM4L9eqDuzmsoYzLUwRXBBhnOE8N
    nFwjzdogqTAO5GIOFf5BnHndNCdXNCMV7PTVPscEVdc9oC1gTvZux+yJ5aQqg/Bx
    KG50NVNedv6qJZivqoFHQB+MMXrXkvxzw/7W1Guw+mkI9IsOtZXrRasfrMEvu++C
    8Mctdhhsdle2Fcd3aXOSVQp0pcJb1N0hnkswpwIDAQABAoIBAFUYD/krb+hviBFj
    TO4N/+tpqTzTLtQ/qZZUqWRscKJ3DBNC5V76DBWYAoiX9ThX5tMp+me4bDuKc9jB
    ozMetx2c50FAwRDE82sx5F/3W52lPafVOgAju09d53A7lCDR6qWuIITRlnHJr7iq
    Eth8qCHyePPbdS3ix9d2ZjJ6aD4YZl5tYSTsF0HJTXrQngKl0WPRzNeicas7nlUr
    v0BGcq3GsWvMSFBG7K8FhLWdZZBP9/vwoAL9gEK8x4ioL6LjB3js7KfoWruJS/gJ
    kLXG3Toa5FkBg8SY6MYIIfrC6wag+0LeXVMVr8ZHw85KJ5bn2ZFLANDxtj8W8V7q
    Ebl+KsECgYEA2sKcreBzrrqrjt2MZVuipYjFu2Fhdnu87ZmP3lCkt/lqsnNA0EWw
    G5eBmE/dQoyWFE8qi1PvyIdVb7N/6HN6B7UYYnYnteXjWHA1yYZgQwBZc5OXH2yf
    jXsntQFkK73+hQO9U/zaGicCbdbXStstan3wboAUPw8aBX/mdsa9SscCgYEA1OBZ
    1m7qM3mJgxskqV1tTEv122sofXP5EShSzFtsjm86CiJFSw2wLFNMn8wjujxkTYDu
    txiDa4Ef5Ee6G/awKw2H6Sp9sIkRTxN/o1toua5o4WOH8h1A/mKp7zJkLmXjU5Ep
    J6rgTOb+MfHLtSWL7QdDsTjna0iasFFPi1biCyECgYBfZHGyGKgZT2k0GUP5huX7
    zRJ8TVCUvAx8h3QG+594Yhi2zC89IsZSodRvOJRBStC+9m6U5vsutGT7GojyMjjK
    V5vUg7V5Sk/C5tttj102mlZnYbqKh3Fj3opIEd0+fdEY67KJhz8MHGqgvwiOqdi6
    EUTgypUJkmpEb6ttq+grTQKBgFJYQogfOXsV7WqIqmLVX/0eeQkaZ3w3y0WmyniA
    ePqT7eiTnyhMMDTFOCOsLLnSuJ3+XNj4o4WHWlXMpSJCB51vy34XUK1kKAzlpv8C
    0fzZiXp+LM0sIcMFWWTMolIMWaYuxbOxdrhotjWNqdX1oy3aHIZGU8Z9PFEt8s4c
    mq3hAoGBALUyLCzHEukYY/3ua/EjA3Qm9fJMJAZr3+8Lh3n4oew7nx1lJjpRCJ5U
    LNDiXfnphEuqRCERR0dOfWBiNlBSpJ09fcRbgDxJWvzsghGc7mODZ04e2/DHfUc0
    MswBDrI4B4f25jZ0aNUGsrtu/pxFPt1XjkAgd43gT9O7o+lb5j6f
    -----END RSA PRIVATE KEY-----
