apiVersion: v1
kind: Secret
metadata:
  name: config-bundle-secret
  namespace: quay-enterprise
stringData:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    BROWSER_API_CALLS_XHR_ONLY: false
    SUPER_USERS:
    - quayadmin
    FEATURE_USER_CREATION: true
    FEATURE_QUOTA_MANAGEMENT: true
    FEATURE_PROXY_CACHE: true
    FEATURE_BUILD_SUPPORT: true
    DEFAULT_SYSTEM_REJECT_QUOTA_BYTES: 102400000
    EXTERNAL_TLS_TERMINATION: true
    FEATURE_UI_V2: true
    AUTHENTICATION_TYPE: OIDC
    OIDC_SERVER: https://oauth-openshift.apps.mays-demo.sandbox508.opentlc.com
    OIDC_CLIENT_ID: quay-client
    OIDC_CLIENT_SECRET: oauth-client-secret
    OIDC_AUTOREGISTER: true
    OIDC_USERNAME_CLAIM: preferred_username
    OIDC_GROUPS_CLAIM: groups
    SERVICE_NAME: OpenShift OAuth
