apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/
  - config-bundle-secret.yaml
  - quay-oauth-client.yaml

patches:
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleLink
      name: quay-enterprise
    patch: |-
      - op: replace
        path: /spec/href
        value: 'https://quay-quay-quay-enterprise.apps.mays-demo.sandbox508.opentlc.com'