apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-permissions
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/ArgoCD-permissions/aggregate/all
    repoURL: 'https://github.com/cmays20/OpenShift-AI-Demo.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true